UPDATE HLSERVICEDISPATCH.TCITY T SET T.FCITY_NAME = '全国' WHERE T.FID='QG';
UPDATE HLSERVICEDISPATCH.TCITY T SET T.FCITY_NAME = '北京' WHERE T.FID='110000';
UPDATE HLSERVICEDISPATCH.TCITY T SET T.FCITY_NAME = '上海' WHERE T.FID='310000';